const imgPath = "./imgs/desktop/listings/";
const linkedin = "./imgs/desktop/listings/linkedin-icon.svg";

export const memberData = [
  {
    profile: `${imgPath}bhanu.png`,
    name: "Bhanu Pratap",
    position: "Founder At Zuriets",
    socialIcon: linkedin,
    starCount: "4.0",
    starCountArray: ["fa-star", "fa-star", "fa-star", "fa-star", "fa-star-o"],
    heading: "Great Value !",
    desc: "We were running short on developers on a critical development project. The Augmnt network helped us by filling the requirements in just 4 days! Unbelievable Value!",
  },
  {
    profile: `${imgPath}karan.png`,
    name: "Karan Bisht",
    position: "Founder At Resource Pool",
    socialIcon: linkedin,
    starCount: "4.5",
    starCountArray: [
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star-half-o",
    ],
    heading: "Always a good experience !",
    desc: "Great amounts of value present by being a part of this network. We recently had 12 React developers and no project to place them on, Luckily we found Augmnt. Ever since, Augmnt’s been our first choice to find projects.",
  },
  {
    profile: `${imgPath}rohnit.png`,
    name: "Rohnit Roy",
    position: "Founder At Digitalite",
    socialIcon: linkedin,
    starCount: "4.0",
    starCountArray: ["fa-star", "fa-star", "fa-star", "fa-star", "fa-star-o"],
    heading: "Brilliant Community !",
    desc: "I’ve always been able to find great developers from Augmnt and high quality that too. I’d recommend this community to all tech service agencies.",
  },
  {
    profile: `${imgPath}chandra.png`,
    name: "Chandra Prakash",
    position: "Founder At C2B",
    socialIcon: linkedin,
    starCount: "4.0",
    starCountArray: ["fa-star", "fa-star", "fa-star", "fa-star", "fa-star-o"],
    heading: "Best Way To Get Business !",
    desc: "Augmnt has become our primary way to find business now. It’s a close knit community, ready to help each other.",
  },
  {
    profile: `${imgPath}akhil.svg`,
    name: "Akhil Pillai",
    position: "Founder At NeoVibe",
    socialIcon: linkedin,
    starCount: "4.0",
    starCountArray: ["fa-star", "fa-star", "fa-star", "fa-star", "fa-star-o"],
    heading: "Tremendously Valuable !",
    desc: "We’ve always found projects through Augmnt. If you’re a tech agency, you’d perpetually be running around for projects, with Augmnt, you don’t have to.",
  },
  {
    profile: `${imgPath}kulkarni.svg`,
    name: "Chinmay Kulkarni",
    position: "Founder At Hybrow Labs",
    socialIcon: linkedin,
    starCount: "4.5 ",
    starCountArray: [
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star-half-o",
    ],
    heading: "Amazing Networking Opportunity",
    desc: "We mostly service  North America based clients and we keep requriing engineers at a short notice. Augmnt has always exceeded our expectations. ",
  },
  {
    profile: `${imgPath}deepak.png`,
    name: "Deepak Thapa",
    position: "Founder At Daynil Group",
    socialIcon: linkedin,
    starCount: "4.5",
    starCountArray: [
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star-half-o",
    ],
    heading: "No Need to Look Anywhere Else",
    desc: "If you’re looking for engineers, this is the place. Hiring short-term contract developers from other agencies is the only sustainable way to grow your business.",
  },
  {
    profile: `${imgPath}chinmay.svg`,
    name: "Chinmay Chandgude",
    position: "Founder At Latent",
    socialIcon: linkedin,
    starCount: "4.0",
    starCountArray: ["fa-star", "fa-star", "fa-star", "fa-star", "fa-star"],
    heading: "Not A Community, But A Family!",
    desc: "This a highly close-knit community, almost like a family. Exchange engineering resources, projects or just network. Augmnt is there to watch your back.",
  },
  {
    profile: `${imgPath}karan.svg`,
    name: "Karan Reddy",
    position: "Founder At AlphaBlockz",
    socialIcon: linkedin,
    starCount: "4.5",
    starCountArray: [
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star",
      "fa-star-half-o",
    ],
    heading: "Awesome Place To Collaborate !",
    desc: "I’ve met so many founders on Augmnt, exchanged business in crores. Great place to network and collaborate for the long term.",
  },
];
